export * from "./Authentication";
export { default as ErrorPage } from "./404Page";
export { default as Home } from "./Home";
export { default as Services } from "./Services";
export { default as Profile } from "./UserProfile";
export { default as WasteDisposal } from "./WasteDisposal";
export { default as WasteRecycling } from "./WasteRecycling";
// export { default as PerfectVolunteer } from "./PerfectVolunteer";
// export { default as SaiKaiTasks } from "./SaiKaiTasks";
// export { default as ConnectWithSaiKai } from "./ConnectWithSaiKai";
// export { default as JobRoles } from "./JobRoles";
// export { default as JobDescription } from "./JobDescription";
// export { default as HelpCenter } from "./HelpCenter";
// export { default as CustomerSupport } from "./CustomerSupport";
// export { default as Application } from "./Profile/Application";
// export { default as Settings } from "./Profile/Settings";
// export { default as LogOut } from "./Profile/LogOut";
